### ISSUE TITLE
Problema guadar proyecto - inscripciones - límite nro máximo de inscripciones

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#43]
Estoy editando las inscripciones de un proyecto, es decir asiganndo categoria y eso y no me deja guardar. dice ERROR INESPERADO, pero no dice cual es el error.
http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/#tab=inscricoes

**Comment by mayteloyarte** [comment]
el error salta cuando pongo el numero máximo de inscripciones autorizadas por agente

**Comment by kterva** [comment]
mensaje del log del servidor 

167.58.64.130 - - [25/Mar/2016:11:23:33 -0300] "GET /assets/img/fundo.png HTTP/1.1" 200 68 "http://mapa-test.cultura.mec.gub.uy:98/assets/css/app-2b004bfc5e2f991beb757cb81f1d7999.css" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:33 -0300] "GET /assets/img/unverified-seal.png HTTP/1.1" 200 2371 "http://mapa-test.cultura.mec.gub.uy:98/assets/css/app-2b004bfc5e2f991beb757cb81f1d7999.css" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:34 -0300] "GET /assets/html/mc-select.html HTTP/1.1" 200 229 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:34 -0300] "GET /assets/html/find-entity.html HTTP/1.1" 304 0 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:34 -0300] "GET /assets/html/edit-box.html HTTP/1.1" 304 0 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:36 -0300] "GET /assets/img/spinner.gif HTTP/1.1" 304 0 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:50 -0300] "GET /assets/img/setinhas-editable.png HTTP/1.1" 200 1008 "http://mapa-test.cultura.mec.gub.uy:98/assets/css/app-2b004bfc5e2f991beb757cb81f1d7999.css" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:50 -0300] "GET /assets/img/clear.png HTTP/1.1" 200 509 "http://mapa-test.cultura.mec.gub.uy:98/assets/css/vendor-e689fb1871f581da0443eb78b4eeaa96.css" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:23:57 -0300] "PUT /projeto/7/ HTTP/1.1" 500 3978 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:24:28 -0300] "PUT /projeto/7/ HTTP/1.1" 500 3978 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:24:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:24:36 -0300] "PUT /projeto/7/ HTTP/1.1" 500 3978 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:25:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:26:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:27:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:28:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:29:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:30:05 -0300] "PUT /projeto/7/ HTTP/1.1" 500 3978 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:30:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"
167.58.64.130 - - [25/Mar/2016:11:31:34 -0300] "GET /api/notification/find/?&@select=id,status,isRequest,createTimestamp,message,approveUrl,request.permissionTo.approve,request.permissionTo.reject,request.requesterUser.id&user=eq(@me)&@ORDER=createTimestamp%20DESC HTTP/1.1" 200 12 "http://mapa-test.cultura.mec.gub.uy:98/projetos/edita/7/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by kterva** [comment]
Slim Application Error
The application could not run because of the following error:

Details

Type: Respect\Validation\Exceptions\ComponentException
Message: "int" is not a valid rule name
File: /srv/mapas/mapasculturais/src/protected/vendor/respect/validation/library/Validator.php
Line: 209
Trace

#0 /srv/mapas/mapasculturais/src/protected/vendor/respect/validation/library/Validator.php(221): Respect\Validation\Validator::buildRule('int', Array)
#1 /srv/mapas/mapasculturais/src/protected/vendor/respect/validation/library/Validator.php(195): Respect\Validation\Validator->__call('int', Array)
#2 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Definitions/Metadata.php(166) : eval()'d code(1): Respect\Validation\Validator::__callStatic('int', Array)
#3 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Definitions/Metadata.php(166) : eval()'d code(1): MapasCulturais\Validator::int()
#4 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Definitions/Metadata.php(166): eval()
#5 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/EntityMetadata.php(290): MapasCulturais\Definitions\Metadata->validate(Object(MapasCulturais\Entities\Project), '15')
#6 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Entity.php(714): MapasCulturais\Entities\Project->getMetadataValidationErrors()
#7 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Traits/MagicGetter.php(23): MapasCulturais\Entity->getValidationErrors()
#8 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(328): MapasCulturais\Entities\Project->__get('validationError...')
#9 [internal function]: MapasCulturais\Controllers\EntityController->PUT_single('7')
#10 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(270): call_user_func_array(Array, Array)
#11 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(169): MapasCulturais\Controller->callAction('PUT', 'single', Array)
#12 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(107): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Project), 'single', Array, false)
#13 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#14 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#15 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#16 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#17 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#18 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#19 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#20 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(397): Slim\Slim->run()
#21 /srv/mapas/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#22 {main}

**Comment by kterva** [comment]
ya fue solucionado

**Comment by mayteloyarte** [comment]
sigue sin funcionar la inscripcion cuando pongo el numero de inscripciones admitidas por agente. Solo admite 0 (ilimitada)

**Comment by mayteloyarte** [comment]
sigue sin funcionar

**Comment by leandrodb** [comment]
@kterva me parece que el error está en respect validation. Hay que atualizar la biblioteca com composer (editando composer.json y ejecutando composer update respect/validation) y puede ser necesario cambiar la regla de validación en la entidad (Project).

**Comment by leandrodb** [comment]
https://packagist.org/packages/respect/validation

**Comment by kterva** [comment]
"v::int()" en la línea 23 de project-types.php hay que cambiarla por "v::intVal()"
